=== restormjs/rest-orm/spec/schema/restormjs.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/restormjs.schema.json",
  "title": "RESTORMJS",
  "description": "JSON Schema for RESTORMJS API specification",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "API specification name"
    },
    "version": {
      "type": "string",
      "description": "API specification version"
    },
    "created": {
      "type": "string",
      "format": "date-time",
      "description": "Timestamp this API specification was created on"
    },
    "description": {
      "type": "string",
      "description": "API specification version"
    },
    "paths": {
      "type": "object",
      "description": "List of API paths supported by specification",
      "patternProperties": {
        "\\w+": {"$ref": "#/definitions/Path"}
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false,

  "definitions": {
    "Field": {
      "type": "object",
      "description": "API Field description and database mapping",
      "properties": {
        "name": {
          "type": "string",
          "description": "Field name"
        },
        "type": {
          "type": "string",
          "description": "Field type",
          "enum": ["number", "string", "boolean"]
        },
        "required": {
          "type": "boolean",
          "description": "Flag indicating whether the field is required"
        },
        "column": {
          "type": "string",
          "description": "DB column name",
          "pattern": "\\w+",
          "maxLength": 128
        },
        "grants": {
          "type": "string",
          "description": "Granted operations on this field",
          "pattern": "C?R?U?",
          "minLength": 1,
          "maxLength": 3
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "type",
        "required",
        "column",
        "grants"
      ]
    },
    "Path": {
      "type": "object",
      "description": "API path description and database mapping",
      "properties": {
        "name": {
          "type": "string",
          "description": "name for api path"
        },
        "path": {
          "type": "string",
          "description": "URL path to this API",
          "pattern": "\\w+",
          "maxLength": 128
        },
        "auth": {
          "type": "boolean",
          "description": "Flag indicating whether api is auth protected so authentication data is required"
        },
        "table": {
          "type": "string",
          "description": "DB table name",
          "pattern": "\\w+",
          "maxLength": 128
        },
        "schema": {
          "type": "string",
          "description": "DB schema name",
          "pattern": "\\w+",
          "maxLength": 128
        },
        "grants": {
          "type": "string",
          "description": "Granted operations on this API",
          "pattern": "C?R?U?D?",
          "minLength": 1,
          "maxLength": 4
        },
        "fields": {
          "type": "object",
          "description": "List of fields available for this API",
          "patternProperties": {
            "\\w+": {"$ref": "#/definitions/Field"}
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "path",
        "auth",
        "table",
        "schema",
        "grants",
        "fields"
      ]
    }
  }
}

=== restormjs/rest-orm/spec/product-api-spec.json
{"name":"restormjs-public APIs","version":"0.0.1","created":"2021-04-03T19:43:18.683Z","description":"Auto generated RESTORMJS api from public schema using restorm-pg-spec","paths":{"customers":{"name":"Customer","path":"customers","auth":true,"table":"customer","schema":"public","grants":"CRUD","fields":{"id":{"name":"id","type":"number","required":true,"column":"id","grants":"CR"},"postalcode":{"name":"postalcode","type":"string","required":false,"column":"postalcode","grants":"CRU"}}},"products":{"name":"Product","path":"products","auth":true,"table":"product","schema":"public","grants":"CRUD","fields":{"id":{"name":"id","type":"number","required":true,"column":"id","grants":"CR"},"price":{"name":"price","type":"string","required":true,"column":"price","grants":"CRU"},"product_name":{"name":"product_name","type":"string","required":true,"column":"product_name","grants":"CRU"},"qty":{"name":"qty","type":"string","required":true,"column":"qty","grants":"CRU"}}},"product_transaction":{"name":"Product_transaction","path":"product_transaction","auth":true,"table":"product_transaction","schema":"public","grants":"CRUD","fields":{"prod_id":{"name":"prod_id","type":"number","required":true,"column":"prod_id","grants":"CR"},"trans_id":{"name":"trans_id","type":"number","required":true,"column":"trans_id","grants":"CR"}}},"transactions":{"name":"Transactions","path":"transactions","auth":true,"table":"transactions","schema":"public","grants":"CR","fields":{"id":{"name":"id","type":"number","required":true,"column":"id","grants":"CR"},"cust_id":{"name":"cust_id","type":"number","required":false,"column":"cust_id","grants":"CRU"},"timedate":{"name":"timedate","type":"string","required":false,"column":"timedate","grants":"CRU"}}}}}

=== restormjs/rest-orm/spec/account-api-spec.json
{"name":"Sample API spec describing account and roles relation","version":"0.0.1","created":"2021-03-24T02:41:41.035Z","description":"Auto generated RESTORMJS api from public schema using restorm-pg-spec","paths":{"account_roles":{"name":"Account_roles","path":"account_roles","auth":false,"table":"account_roles","schema":"public","grants":"CRUD","fields":{"grant_date":{"name":"grant_date","type":"string","required":false,"column":"grant_date","grants":"CRU"},"role_id":{"name":"role_id","type":"number","required":true,"column":"role_id","grants":"CRU"},"user_id":{"name":"user_id","type":"number","required":true,"column":"user_id","grants":"CRU"}}},"accounts":{"name":"Accounts","path":"accounts","auth":false,"table":"accounts","schema":"public","grants":"CRUD","fields":{"id":{"name":"id","type":"number","required":false,"column":"user_id","grants":"CRU"},"created_on":{"name":"created_on","type":"string","required":true,"column":"created_on","grants":"CRU"},"email":{"name":"email","type":"string","required":true,"column":"email","grants":"CRU"},"last_login":{"name":"last_login","type":"string","required":false,"column":"last_login","grants":"CRU"},"password":{"name":"password","type":"string","required":true,"column":"password","grants":"CRU"},"username":{"name":"username","type":"string","required":true,"column":"username","grants":"CRU"}}},"roles":{"name":"Roles","path":"roles","auth":false,"table":"roles","schema":"public","grants":"CRUD","fields":{"id":{"name":"id","type":"number","required":false,"column":"role_id","grants":"CRU"},"role_name":{"name":"role_name","type":"string","required":true,"column":"role_name","grants":"CRU"}}}}}

=== restormjs/rest-orm/test/test-api-spec.json
{
  "name":"RESTORMJS Test API Spec",
  "version":"0.0.1",
  "created":"2021-03-05T05:09:07.729Z",
  "description":"A simple spec for unit tests",
  "paths":{
    "account_roles":{
      "name":"Account_roles",
      "path":"account_roles",
      "protected":false,
      "db_table":"account_roles",
      "db_schema":"public",
      "operations":"CRUD",
      "fields":{
        "grant_date":{
          "name":"grant_date",
          "type":"string",
          "is_required":false,
          "column_name":"grant_date"
        },
        "role_id":{
          "name":"role_id",
          "type":"number",
          "is_required":true,
          "column_name":"role_id"
        },
        "user_id":{
          "name":"user_id",
          "type":"number",
          "is_required":true,
          "column_name":"user_id"
        }
      }
    },
    "accounts":{
      "name":"Accounts",
      "path":"accounts",
      "protected":false,
      "db_table":"accounts",
      "db_schema":"public",
      "operations":"CRUD",
      "fields":{
        "id":{
          "name":"id",
          "type":"number",
          "is_required":false,
          "column_name":"user_id"
        },
        "created_on":{
          "name":"created_on",
          "type":"string",
          "is_required":true,
          "column_name":"created_on"
        },
        "email":{
          "name":"email",
          "type":"string",
          "is_required":true,
          "column_name":"email"
        },
        "last_login":{
          "name":"last_login",
          "type":"string",
          "is_required":false,
          "column_name":"last_login"
        },
        "password":{
          "name":"password",
          "type":"string",
          "is_required":true,
          "column_name":"password"
        },
        "username":{
          "name":"username",
          "type":"string",
          "is_required":true,
          "column_name":"username"
        }
      }
    },
    "roles":{
      "name":"Roles",
      "path":"roles",
      "protected":false,
      "db_table":"roles",
      "db_schema":"public",
      "operations":"CRUD",
      "fields":{
        "id":{
          "name":"id",
          "type":"number",
          "is_required":false,
          "column_name":"role_id"
        },
        "role_name":{
          "name":"role_name",
          "type":"string",
          "is_required":true,
          "column_name":"role_name"
        }
      }
    }
  }
}

=== restormjs/rest-orm/spec/playground-api-spec.json
{
  "name": "Sample api spec describing playground table",
  "version": "0.0.1",
  "created": "2021-03-16T02:33:26.778Z",
  "description": "Auto generated RESTORMJS api from public schema using restorm-pg-spec",
  "paths": {
    "playgrounds": {
      "name": "Playground",
      "path": "playgrounds",
      "auth": false,
      "table": "playground",
      "schema": "public",
      "grants": "CRUD",
      "fields": {
        "id": {
          "name": "id",
          "type": "number",
          "required": false,
          "column": "equip_id",
          "grants": "CRU"
        },
        "color": {
          "name": "color",
          "type": "string",
          "required": true,
          "column": "color",
          "grants": "CRU"
        },
        "install_date": {
          "name": "install_date",
          "type": "string",
          "required": false,
          "column": "install_date",
          "grants": "CRU"
        },
        "location": {
          "name": "location",
          "type": "string",
          "required": false,
          "column": "location",
          "grants": "CRU"
        },
        "type": {
          "name": "type",
          "type": "string",
          "required": true,
          "column": "type",
          "grants": "CRU"
        }
      }
    }
  }
}

=== restormjs/rest-orm/api-spec.json
{"name":"Horizon API","version":"0.0.1","created":"2021-02-17T04:58:39.921Z","description":"Auto generated horizon api from public db schema using db2api","paths":{"playground":{"name":"Playground","path":"playground","protected":false,"db_table":"playground","db_schema":"public","operations":"CRUD","fields":{"id":{"name":"id","type":"number","is_required":false,"column_name":"equip_id"},"color":{"name":"color","type":"string","is_required":true,"column_name":"color"},"install_date":{"name":"install_date","type":"string","is_required":false,"column_name":"install_date"},"location":{"name":"location","type":"string","is_required":false,"column_name":"location"},"type":{"name":"type","type":"string","is_required":true,"column_name":"type"}}}}}
